{% set version = "2.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wikidatar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WikidataR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WikidataR/WikidataR_{{ version }}.tar.gz
  sha256: dd349d160c1c0bae9e3efa336efc622ea9dd481cc0a449ceab49852d220eb2da

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-wikidataqueryservicer
    - r-wikipedir
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-pbapply
    - r-readr
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-hmisc
    - r-wikidataqueryservicer
    - r-wikipedir
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-pbapply
    - r-readr
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('WikidataR')"           # [not win]
    - "\"%R%\" -e \"library('WikidataR')\""  # [win]

about:
  home: https://github.com/TS404/WikidataR/issues
  license: MIT
  summary: An API client for the Wikidata <https://www.wikidata.org/wiki/Wikidata:Main_Page> store of semantic data.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - ocefpaf
