{% set version = "2.1.5" %}

package:
  name: r-wikidatar
  version: {{ version }}

source:
  fn: WikidataR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/WikidataR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/WikidataR/WikidataR_{{ version }}.tar.gz
  sha256: d3939806bd83c035bed52816732a9b5cc71ab4d6a499a70fbb23f7865f4b06b7

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-wikipedir >=1.4.0
    - r-httr
    - r-jsonlite
  run:
    - r-base
    - r-wikipedir >=1.4.0
    - r-httr
    - r-jsonlite

test:
  commands:
    - $R -e "library('WikidataR')"  # [not win]
    - "\"%R%\" -e \"library('WikidataR')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/wikidatar
  license: MIT
  license_file: LICENSE
  summary: An API client for the Wikidata

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - ocefpaf
