# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KXIMm1qRWGLYw7XU/+64T2PGFPwt+vgwb3r4ynB3jFsFmgW5leiL91SYHgJhz8xNK6RtcCgjz/YShDiici+mrTiSbrfeWUd+0VukxDvV2I02KuR7Qh+1n+KrEIXGH3LRCOZbaNSdKzQAvTO8dCtoVgRtqbWE6eTRFn5PjAi6ngFM6WGBzSaFYn1Kc/9RF6efspd1GlLN6nzevFXfRY6vKfll/h5w7EFzTTpow/t1YqTUXh2bzki0rcraIoNetRvtaFrdgXinVF3mKGoM9zyV9N1TikRropj35+AGBWSPhbZ5F4vGKG8nDkua+QcazrvZRM0mhZF/rODGRRdTmJO3exko64atDQdi1yP+cZ+Fpl9ya3VDIdoPHRoAqchaM0hdWsC6yIK4zM1IO1iRvRQ8pLKgNzC0JSZQ80B7mXuQqrlsmVKEQGgEiCwhDg1bTvQYp1VrcD9G6hS0KC/OskbI/+ze8MqQlCAu0n28Bzb2bzVuZu6ssx22zpuHEy/CbVjsnQmvQgR2u4zUg/jxpePetO8nl2ETQIQfm5T8jQLCYFxJev6NJx/I7qP10VWp7ep45VXiWSjt2xC1OkCfuSUPzAzFtxJFAZKukHYPK0PWef3jr739jpSSkniYvrjNCkHBEYNaQvoChqDAcdQleiUK4LFd5DYeksPtn9BZqtDbHx4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
