appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: KXIMm1qRWGLYw7XU/+64T2PGFPwt+vgwb3r4ynB3jFsFmgW5leiL91SYHgJhz8xNK6RtcCgjz/YShDiici+mrTiSbrfeWUd+0VukxDvV2I02KuR7Qh+1n+KrEIXGH3LRCOZbaNSdKzQAvTO8dCtoVgRtqbWE6eTRFn5PjAi6ngFM6WGBzSaFYn1Kc/9RF6efspd1GlLN6nzevFXfRY6vKfll/h5w7EFzTTpow/t1YqTUXh2bzki0rcraIoNetRvtaFrdgXinVF3mKGoM9zyV9N1TikRropj35+AGBWSPhbZ5F4vGKG8nDkua+QcazrvZRM0mhZF/rODGRRdTmJO3exko64atDQdi1yP+cZ+Fpl9ya3VDIdoPHRoAqchaM0hdWsC6yIK4zM1IO1iRvRQ8pLKgNzC0JSZQ80B7mXuQqrlsmVKEQGgEiCwhDg1bTvQYp1VrcD9G6hS0KC/OskbI/+ze8MqQlCAu0n28Bzb2bzVuZu6ssx22zpuHEy/CbVjsnQmvQgR2u4zUg/jxpePetO8nl2ETQIQfm5T8jQLCYFxJev6NJx/I7qP10VWp7ep45VXiWSjt2xC1OkCfuSUPzAzFtxJFAZKukHYPK0PWef3jr739jpSSkniYvrjNCkHBEYNaQvoChqDAcdQleiUK4LFd5DYeksPtn9BZqtDbHx4=
conda_forge_output_validation: false
